### ISSUE TITLE
Please if isn't a problem port this tool to install magisk on gsis

### ISSUE THREAD

**Issue by Skorpion96** [nitanmarcel/waydroid-magisk#12]
**Is your feature request related to a problem? Please describe.**
I have a phone with locked bl, and this is a problem as i'm unable to install magisk in any way, also boot doesn't even have a ramdisk.
**Describe the solution you'd like**
This tool you made could be the solution to my and other people problem, i have phh-su so if the tool could install magisk from a shell would be great, note that i don't have /sbin
**Describe alternatives you've considered**
I tried many alternatives, magisk delta doesn't work because gsis are on f2fs, i tried to install magisk files manually but magisk doesn't want to work, i tried to patch recovery as well but when i do the process to boot in magisk mode i always get in recovery. For all these issues a "magisk on gsi" tool on github is needed
**Additional context**

**Comment by nitanmarcel** [comment]
The proiect was mainly done for Waydroid and I don't have any plans to use it android.

Anyway the idea it's pretty simple: place the binaries into their places in `/system/etc/init/magisk` and replace the init.rc with the Magisk one.

**Comment by nitanmarcel** [comment]
You can find the binaries after unpacking the magisk apk, under the libs folder/{your phone architecture)

And for init.rc you'll need:

```bash
on post-fs-data
	start logd
	exec u:r:su:s0 root root -- /system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk
	exec u:r:su:s0 root root -- /system/etc/init/magisk/magiskpolicy --live --magisk "allow * magisk_file lnk_file *"
	mkdir /sbin/.magisk 700
	mkdir /sbin/.magisk/mirror 700
	mkdir /sbin/.magisk/block 700
	copy /system/etc/init/magisk/config /sbin/.magisk/config
	rm /dev/.magisk_unblock
	start kBveseXEGX0Wuaj
	wait /dev/.magisk_unblock 40
	rm /dev/.magisk_unblock


service kBveseXEGX0Wuaj /sbin/magisk --auto-selinux --post-fs-data
	user root
	seclabel u:r:su:s0
	oneshot


service gy4aazawjGxaeCs /sbin/magisk --auto-selinux --service
	class late_start
	user root
	seclabel u:r:su:s0
	oneshot


on property:sys.boot_completed=1
	mkdir /data/adb/magisk 755
	exec u:r:su:s0 root root -- /sbin/magisk --auto-selinux --boot-complete


on property:init.svc.zygote=restarting
	exec u:r:su:s0 root root -- /sbin/magisk --auto-selinux --zygote-restart

on property:init.svc.zygote=stopped
	exec u:r:su:s0 root root -- /sbin/magisk --auto-selinux --zygote-restart
```

**Comment by Skorpion96** [comment]
Many thanks, I'll give it a try and if I will have any issues I'll report back hoping to not harass you

**Comment by Skorpion96** [comment]
Ok so there is the first issue, i pushed all files and modified the init.rc, but i'm having sepolicy issues, here a photo of the issue
![photo_2023-07-04_23-53-58](https://github.com/nitanmarcel/waydroid-magisk/assets/39702358/aef706a2-24c7-4981-9923-7dc7530beca7)

**Comment by nitanmarcel** [comment]
`./magiskpolicy --load /vendor/etc/selinux/precompiled_sepolicy --live --magisk`

In /etc/init/magisk, where you have magiskpolicy binary, make it executable (`chmod +x`)

**Comment by Skorpion96** [comment]
About this ./magiskpolicy --load /vendor/etc/selinux/precompiled_sepolicy --live --magisk
I found the precompiled sepolicy, should I add that command to init.rc? And if yes I can copy paste it with the path edited or I should add some cd to /vendor/etc/selinux?

**Comment by Skorpion96** [comment]
i pasted that command but i still got the previous error, here is my init.rc
[init.rc.txt](https://github.com/nitanmarcel/waydroid-magisk/files/11956918/init.rc.txt)

**Comment by nitanmarcel** [comment]
What the hell is that?

**Comment by nitanmarcel** [comment]
Oh my bad. It's bootanim.rc

**Comment by Skorpion96** [comment]
well i did the craziest thing possible adding before everything on init.rc the "setenforce 0" command but i still get that error abot sepolicy. I'll try with setenforce permissive and report back
