### ISSUE TITLE
error upon running make install USE_SYSTEMD=1

### ISSUE THREAD

**Issue by giri256** [nitanmarcel/waydroid-magisk#14]
i have the waydroid installed and working from the AUR, I wanted to root that.

git cloned this repo
cd 
sudo make install USE_SYSTEMD=1

i get this error:
if [ -f /sys/fs/selinux/enforce ]; then \
        echo "Magisk Delta is not compatible with SELinux on Waydroid."; \
        exit 1; \
fi
install -d /usr/bin
install -m 755 waydroid_magisk.py /usr/bin/waydroid_magisk
if [ 1 = 1 ]; then \
        install -d /usr/lib/systemd/system; \
        cp waydroid_magisk_ota.service /usr/lib/systemd/system; \
fi
if [ 0 = 1 ]; then \
        install -d /etc/init; \
        cp waydroid_magisk_ota.conf /etc/init; \
fi

**Comment by nitanmarcel** [comment]
That's not an error

**Comment by bocsi** [comment]
disable SElinux, Won't install if you have it enabled.

**Comment by DaRandomCube** [comment]
getenforce returns disabled but still cannot install

**Comment by nitanmarcel** [comment]
> getenforce returns disabled but still cannot install

You need to disable it permanently:

Add `SELINUX=disabled` in `/etc/selinux/config`

**Comment by DaRandomCube** [comment]
it's not working too
here is my  `/etc/selinux/config`
![image](https://github.com/nitanmarcel/waydroid-magisk/assets/93283139/3a9751dc-7143-4cd7-a14e-8222b96a2a0b)

**Comment by nitanmarcel** [comment]
> it's not working too here is my `/etc/selinux/config` ![image](https://user-images.githubusercontent.com/93283139/270109469-3a9751dc-7143-4cd7-a14e-8222b96a2a0b.png)

Have you rebooted after?

**Comment by DaRandomCube** [comment]
yes
2 times

**Comment by DaRandomCube** [comment]
also i've did `sudo grubby --update-kernel ALL --args selinux=0`
still not working

**Comment by nitanmarcel** [comment]
> also i've did `sudo grubby --update-kernel ALL --args selinux=0` still not working

Are you sure Magisk isn't installed?

**Comment by nitanmarcel** [comment]
`waydroid_magisk status`

**Comment by DaRandomCube** [comment]
![image](https://github.com/nitanmarcel/waydroid-magisk/assets/93283139/afbf0f4b-01bb-46e5-bffa-e09994594279)
not installed

**Comment by nitanmarcel** [comment]
> ![image](https://user-images.githubusercontent.com/93283139/270121076-afbf0f4b-01bb-46e5-bffa-e09994594279.png) not installed

`sudo umount/sys/fs/selinux` until I get the time to fix it

**Comment by DaRandomCube** [comment]
![image](https://github.com/nitanmarcel/waydroid-magisk/assets/93283139/12675b97-fd86-4abd-b0d0-cc5321adb7e5)
