### ISSUE TITLE
Magisk daemon not launching properly?

### ISSUE THREAD

**Issue by Xag8031** [nitanmarcel/waydroid-magisk#18]
**Describe the bug**
waydroid_magisk status shows as daemon running, no root access in apps and magisk delta.
In /system/etc/init/magisk, both magisk32 and magisk64 shows No daemon running.

**To Reproduce**
Install waydroid with waydroid init
waydroid boots for first time
Install magisk with sudo waydroid_magisk install
Run sudo waydroid_magisk setup as instructed.

**Expected behavior**
Magisk should show a running daemon in the os.

**Logs**
```
10-10 18:36:07.397   187   187 I : Magisk 0fe46c5a-delta(26301) daemon started
10-10 18:36:07.397   187   187 I : * Device API level: 30
10-10 18:36:07.398   187   187 I : * CPU ABI 64-bit: x86_64,arm64-v8a
10-10 18:36:07.398   187   187 I : * CPU ABI 32-bit: x86,armeabi-v7a,armeabi
10-10 18:36:21.187   187   192 I : ** boot-complete triggered
```

**Desktop (please complete the following information):**
 - OS: `Linux  6.5.5-x64v2-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Thu, 05 Oct 2023 20:25:13 +0000 x86_64 GNU/Linux`
 - Version: 1.2.10
- Waydroid Version: waydroid-1.4.1-1
-
**Additional context**
I've tried uninstalling and reinstalling waydroid 
I've tried uninstalling and reinstalling magisk

**Comment by Xag8031** [comment]
Fixed by installing via waydroid script, closing!

**Comment by nitanmarcel** [comment]
> Fixed by installing via waydroid script, closing!

Weird, they both use the same Magisk version.
