### ISSUE TITLE
error upon running sudo waydroid_magisk setup   bug

### ISSUE THREAD

**Issue by AnujMuth** [nitanmarcel/waydroid-magisk#21]
phablet@ubuntu-phablet:~$ sudo waydroid magisk setup [sudo] password for phablet:
Permission denied - Failed to rexec as menfd free(): invalid pointer
permission denied • Failed to rexec as memfd free(): invalid pointer
permission denied - Failed to rexec as memfd free(): invalid pointer
Permission denied • Failed to rexec as memfd free(): invalid pointer
Permission denied - Failed to rexec as menfd free(): invalid pointer
Permission denied • Failed to rexec as menfd free: invalid pointer
[10:50:07] - INFO - Restarting Waydroid in 5 (press ^
C to cancel)
[10:50:08] - INFO - Restarting Waydroid in 4 (press ^
C to cancel)
[10:50:09] - INFO - Restarting Waydroid in 3 (press ^
C to cancel)
[10:50:10] - INFO - Restarting Waydroid in 2 (press ^
C to cancel)
[10:50:11] - INFO - Restarting Waydroid in 1 (press ^
C to cancel)
[10:50:12] - INFO - Stopping Waydroid
10:50:14] - INFO - Starting Waydroid

ubuntu touch ota3        
 fxtex pro1x 
 
What should I do, teach me, thank you.

**Comment by nitanmarcel** [comment]
Does `sudo waydroid shell` works?

**Comment by AnujMuth** [comment]
> Does `sudo waydroid shell` works?

no,Same error message “Permission denied - Failed to rexec as menfd free(): invalid pointer”

**Comment by nitanmarcel** [comment]
> > Does `sudo waydroid shell` works?
> 
> no,Same error message “Permission denied - Failed to rexec as menfd free(): invalid pointer”

Seems that something is broken on your system.

Maybe try opening an issue at https://github.com/waydroid/waydroid

**Comment by roc-gui** [comment]
This may be due to link deprecation.
The repository "HuskyDG/magisk-files" has renamed to "HuskyDG/magisk-files.old". And already been archived.
https://github.com/HuskyDG/magisk-files.old
Maybe change those links will fix this issue temporarily.

**Comment by nitanmarcel** [comment]
> This may be due to link deprecation. The repository "HuskyDG/magisk-files" has renamed to "HuskyDG/magisk-files.old". And already been archived. https://github.com/HuskyDG/magisk-files.old Maybe change those links will fix this issue temporarily.

Thanks for letting me know. I've updated the URL

**Comment by nitanmarcel** [comment]
Please check the latest built, see if it works now

**Comment by anonfishe** [comment]
I have the exact same issue, Ubuntu Touch 20.04 stable OTA-3, on Redmi Note 9 Pro (global), tried today

**Comment by nitanmarcel** [comment]
I'm going to close this as incomplete. Please open a proper issue with logs
