### ISSUE TITLE
error on bazzite 39 (silverblue fedora 39)

### ISSUE THREAD

**Issue by DarkenLX** [nitanmarcel/waydroid-magisk#26]
**Describe the bug**
if [ -f /sys/fs/selinux/enforce ]; then \
        echo "Kitsune Mask is not compatible with SELinux on Waydroid."; \
        exit 1; \
fi
Kitsune Mask is not compatible with SELinux on Waydroid.
make: *** [Makefile:18: check_selinux] Error 1

**To Reproduce**
1. follow install guide
2. run sudo make install USE_SYSTEMD=1
3. See error 

note: selinux is set to permissive

**Comment by nitanmarcel** [comment]
You need to disable SELinux. Anyway Kitsune Mask doesn't currently on Waydroid.
