### ISSUE TITLE
enhancement: systemd flags in readme

### ISSUE THREAD

**Issue by gaussandhisgun** [nitanmarcel/waydroid-magisk#4]
just a little headsup for the readme.md:

> For systemd `sudo systemctl enable waydroid_magisk_ota.service && sudo systemctl start waydroid_magisk_ota.service`

you dont need to run start after enable, because enable has this handy `--now` flag:

`systemctl enable --now waydroid_magisk_ota.service` will both enable *and* start the service

**Comment by nitanmarcel** [comment]
Thanks for reminding me. I noticed that but I forgot to edit it :)
