### ISSUE TITLE
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "service"

### ISSUE THREAD

**Issue by Just-A-Pony** [nitanmarcel/waydroid-magisk#6]
**Describe the bug**

systemctl start waydroid-container.service

sudo waydroid_magisk.py install
```
[16:51:41] - INFO - Downloading Magisk Delta: canary-80855189-delta
[16:51:42] - INFO - Extracting Magisk Delta
[16:51:42] - INFO - Installing Magisk Delta
[16:51:42] - INFO - Backing up bootanim.rc
[16:51:42] - INFO - Patching bootanim.rc
[16:51:42] - INFO - Finishing installation
[16:51:42] - INFO - Done
[16:51:42] - INFO - Run waydroid_magisk setup after waydroid starts again or install Magisk Delta Manager
```
waydroid show-full-ui
sudo waydroid_magisk.py setup
```
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - ERROR - Magisk Delta is not installed
[16:53:08] - INFO - Stopping Waydroid in 5 (press ^C to cancel)
[16:53:09] - INFO - Stopping Waydroid in 4 (press ^C to cancel)
[16:53:10] - INFO - Stopping Waydroid in 3 (press ^C to cancel)
[16:53:11] - INFO - Stopping Waydroid in 2 (press ^C to cancel)
[16:53:12] - INFO - Stopping Waydroid in 1 (press ^C to cancel)
[16:53:13] - INFO - Stopping waydroid
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "service"
[16:53:13] - INFO - Starting Waydroid
```
Now,if i install nagisk delta manually from apk in the waydroid,it will show
![图片](https://user-images.githubusercontent.com/51501756/215315935-c40c42c4-b401-4426-a294-b28a5b554ef3.png)
If i ckick "ok", "dirct install into system partition",
![图片](https://user-images.githubusercontent.com/51501756/215316157-9d445383-5758-49e3-9aa1-a9ccf940e9f4.png)
if i ctrl+c `waydroid show-full-ui` ,and rerun `sudo waydroid_magisk.py install`,
```
[17:04:43] - ERROR - Magisk Delta already installed!
```
**Logs**
From `sudo waydroid_magisk log --save`
No,it will show `[17:04:14] - ERROR - Magisk Delta is not installed`
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Arch Linux with linux-xanmod-anbox
- Waydroid Version: [e.g. 1.4.0] 1.3.4

**Additional context**

**Comment by Just-A-Pony** [comment]
https://drive.google.com/file/d/1IzjPT9Q9XrGycC-C3ow-NaUHjLmccexG/view?usp=sharing
https://drive.google.com/file/d/1SZHD8O-q3gPvn4JNIT11H19bG2jfSgca/view?usp=sharing
/usr/share/waydroid-extra/images/

**Comment by nitanmarcel** [comment]
Are the images used clean? Meaning no other modifications applied to it.

Also a cleanup with `rm -rf /var/lib/waydroid` and `sudo waydroid init` should probably fix it, as it seems something went wrong when installing Magisk

**Comment by nitanmarcel** [comment]
Also. The setup lines where it says that Magisk is not installed, shouldn't be spammed. Make sure you're using the last version since that bug was fixed a few earlier commits

```

**Comment by nitanmarcel** [comment]
Oh sorry.

The last two commits should fix it. Instead of cleaning the images you can do (after updating waydroid-magisk)

`sudo waydroid_magisk remove`

Then start everything based by the instructions.

**Comment by nitanmarcel** [comment]
And about the Magisk Delta Manager error. I've moved the FAQ related to it from the `Ubuntu Touch` section to a section of it's own.

https://github.com/nitanmarcel/waydroid-magisk#magisk-delta-fails-to-patch-selinux-policy

**Comment by Just-A-Pony** [comment]
> Oh sorry.
> 
> The last two commits should fix it. Instead of cleaning the images you can do (after updating waydroid-magisk)
> 
> `sudo waydroid_magisk remove`
> 
> Then start everything based by the instructions.

Thanks! it works!
```
[21:19:59] - INFO - Daemon: Running
[21:19:59] - INFO - Magisk Version: 80855189-delta:MAGISKSU
```
But there's still a ` lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "service" ` during the `waydroid_magisk.py setup`
```
[21:19:08] - INFO - Stopping Waydroid in 5 (press ^C to cancel)
[21:19:09] - INFO - Stopping Waydroid in 4 (press ^C to cancel)
[21:19:10] - INFO - Stopping Waydroid in 3 (press ^C to cancel)
[21:19:11] - INFO - Stopping Waydroid in 2 (press ^C to cancel)
[21:19:12] - INFO - Stopping Waydroid in 1 (press ^C to cancel)
[21:19:13] - INFO - Stopping waydroid
lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "service"
[21:19:13] - INFO - Starting Waydroid
```

**Comment by nitanmarcel** [comment]
Ignore that. I should probably silence it

**Comment by nitanmarcel** [comment]
Actually @Just-A-Pony in `sudo waydroid shell` can you do `which service` and send me the output?

Thanks

**Comment by Just-A-Pony** [comment]
> 

` /system/bin/service `
And if I run ` service call waydroidhardware 4 `manually,It seams worls properly which restart the waydroid

**Comment by Just-A-Pony** [comment]
I found this in [archwiki](https://wiki.archlinux.org/title/Linux_Containers#Error:_unknown_command) : 

> The error may happen when a basic command (ls, cat, etc.) on an attached container is typed hen a different Linux distribution is containerized relative to the host system (e.g. Debian container in Arch Linux host system). Upon attaching, use the argument --clear-env: 
> `lxc-attach -n container_name --clear-env`

**Comment by nitanmarcel** [comment]
> I found this in [archwiki](https://wiki.archlinux.org/title/Linux_Containers#Error:_unknown_command) :
> 
> > **5.3 Error: unknown command**
> > The error may happen when a basic command (ls, cat, etc.) on an attached container is typed hen a different Linux distribution is containerized relative to the host system (e.g. Debian container in Arch Linux host system). Upon attaching, use the argument --clear-env:
> > `lxc-attach -n container_name --clear-env`

Oh. My bad there. It seems I forgot to pass the env argument in subprocess.run

**Comment by nitanmarcel** [comment]
> I found this in [archwiki](https://wiki.archlinux.org/title/Linux_Containers#Error:_unknown_command) :
> 
> > **5.3 Error: unknown command**
> > The error may happen when a basic command (ls, cat, etc.) on an attached container is typed hen a different Linux distribution is containerized relative to the host system (e.g. Debian container in Arch Linux host system). Upon attaching, use the argument --clear-env:
> > `lxc-attach -n container_name --clear-env`

this should be also fixed now
